name: application-build
on:
    push:
        branches:
            - main
jobs:
    docker:
        uses: ./github/workflows/reusable-ci.yaml@v1
        with:
            image_name: reusable-workflow
            image_tag: ${{github.sha}}
        secrets:
            registry_username: ${{secrets.REGISTRY_USERNAME }}
            registry_password: ${{secrets.REGISTRY_PASSWORD}}
